### PR TITLE
Add Manifest.in to include *.md files in the source tarball

### PR DESCRIPTION
**Pull request by zachcp**
Hi @alorence ,

I was just attempting to package this up for conda and ran into an issue with the package on pypi. The source does not have the README.md file which is called by setup.py.  This triggers an error in the conda build system.

This PR simply adds a manifest file telling setuptools to include the *.MD.

Do you think you could rebuild and upload to pypi?

thanks,
zach cp

### CODE REVIEW

**Comment by alorence** [comment]
Hi @zachcp,

Thank you very much for your contribution. I'm happy to see this little repository is useful to somebody else than me ;) I will merge your pull request, but I will cancel the version bump. Since the original [pysvg has version 0.2.2 on Pypy](https://pypi.python.org/pypi/pysvg/0.2.2), I don't want to bump this fork to version 0.2.3.

I will instead append a suffix to the version number, according to [SemVer](https://semver.org) specifications.

**Comment by alorence** [comment]
The new release is available on [pypi.org](https://pypi.org/project/pysvg-py3/) and on [pypi.python.org](https://pypi.python.org/pypi/pysvg-py3).

Hope this help. Tell me if you need another update on built package.

**Comment by zachcp** [comment]
Thanks @alorence ! Much appreciated.

**Comment by zachcp** [comment]
@alorence . can you pip install your newly built package?

```
# works fine
pip install pysg-py3

# 
from pysvg.core import BaseElement
ModuleNotFoundError: No module named 'pysvg'
```

**Comment by alorence** [comment]
I confirm I can install the new version. Then I can import from pysvg.* in my python code.

Can you make sur the library has been correctly installed in site-package (in your virtual env or in main python site-package dir)?

pycharm64_2018-04-05_22-58-42

**Comment by zachcp** [comment]
@alorence,

yes, I can build and import locally as well now (both pip and conda.). However,  when building on conda-forge this error is still being [triggered](https://github.com/conda-forge/staged-recipes/pull/5581).   The only thing I can think of is that the [current version](https://github.com/alorence/pysvg-py3/blob/master/setup.py#L17) is set to "0.2.2-rev1" while the package is set to "0.2.2.post1".   Is it possible to set these two to be identical? I will also enquire on the Conda-forge mailing lists to see if this is an issue.

Thanks for your time & prompt feedback.
zach cp

Note: it appears that in the logs the name is ["normalized" ](https://circleci.com/gh/conda-forge/staged-recipes/25582?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link )which is what happening on my local machine.  So I think there may be some other issue.  I will post an issue on conda-forge.

**Pull request merged**
